package com.luke.master.entitys;

import java.util.List;

import org.springframework.context.annotation.Lazy;

import com.luke.master.utils.Constants;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "ROLES", schema = Constants.SCHEMA, catalog = "")
public class Roles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ROLES_SEQ")
	@SequenceGenerator(sequenceName = "roles_seq", allocationSize = 1, name = "ROLES_SEQ")
	@Getter
	@Setter
	public Long id;

	@Column(name = "CODE", length = 15)
	@Getter
	@Setter
	public String code;

	@Column(name = "DESCR", length = 35)
	@Getter
	@Setter
	public String descr;

	@OneToMany(mappedBy = "roles", fetch = FetchType.LAZY)
	@Getter
	@Setter
	@Lazy
	public List<Usuarios> usuarios;

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "CAPABILITYANDROLE", schema = Constants.SCHEMA, joinColumns = @JoinColumn(name = "ID_ROLE"), inverseJoinColumns = @JoinColumn(name = "ID_CAPABILITY"))
	@Getter
	@Setter
	@Lazy
	public List<Capabilityes> capabilities;

}
