
BEGIN;

-------------------- FICHA TIPO UNIDAD ORGANIZATIVA ------------------------------------------------------
-- tipos de UNIDAD ORGANIZATIVA ------- 
INSERT INTO bssos.REPO_TIPO_UNIDADES_ORG
(CD_TIPO_UNIDAD_ORG, TX_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('DIR', 'Direccion', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');

INSERT INTO bssos.REPO_TIPO_UNIDADES_ORG
(CD_TIPO_UNIDAD_ORG, TX_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('SDIR', 'Subdireccion', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');

INSERT INTO bssos.REPO_TIPO_UNIDADES_ORG
(CD_TIPO_UNIDAD_ORG, TX_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('SERV', 'Servicio', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');

INSERT INTO bssos.REPO_TIPO_UNIDADES_ORG
(CD_TIPO_UNIDAD_ORG, TX_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('DPTO', 'Departamento', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');

INSERT INTO bssos.REPO_TIPO_UNIDADES_ORG
(CD_TIPO_UNIDAD_ORG, TX_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('DIST', 'Distrito', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');

INSERT INTO bssos.REPO_TIPO_UNIDADES_ORG
(CD_TIPO_UNIDAD_ORG, TX_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('COOR', 'Coordinacion', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');


-------------------- FICHA REPO_UNIDADES_ORG ------------------------------------------------------
--  REPO_UNIDADES_ORG ------- 

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000002', 'Distrito de Centro', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10006943', 'Coordinación del Distrito Centro', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000002') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219029', 'Servicio de Servicios a la Ciudadanía del Distrito Centro', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10006943') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10006955', 'Departamento Servicios Sociales del Distrito Centro', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10219029') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000003', 'Distrito de Arganzuela', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10006150', 'Coordinación del Distrito Arganzuela', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000003') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219034', 'Servicio de Servicios a la Ciudadanía del Distrito Arganzuela', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10006150') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10006955', 'Departamento Servicios Sociales del Distrito Arganzuela', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10219034') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000004', 'Distrito de Retiro', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10006153', 'Coordinación del Distrito Retiro', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000004') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219039', 'Servicio de Servicios a la Ciudadanía del Distrito Retiro', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10006153') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10006986', 'Departamento Servicios Sociales del Distrito Retiro', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10219039') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000005', 'Distrito de Salamanca', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10006991', 'Coordinación del Distrito Salamanca', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000005') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219044', 'Servicio de Servicios a la Ciudadanía del Distrito Salamanca', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10006991') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007003', 'Departamento Servicios Sociales del Distrito Salamanca', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10219044') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000006', 'Distrito Chamartin', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10006154', 'Coordinación del Distrito Chamartin', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000006') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10218744', 'Servicio de Servicios a la Ciudadanía del Distrito Chamartin', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10006154') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007019', 'Departamento Servicios Sociales del Distrito Chamartin', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10218744') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000007', 'Distrito Tetuán', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007023', 'Coordinación del Distrito Tetuán', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000007') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10218749', 'Servicio de Servicios a la Ciudadanía del Distrito Tetuán', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007023') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007035', 'Departamento Servicios Sociales del Distrito Tetuán', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10218749') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000008', 'Distrito Chamberí', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007039', 'Coordinación del Distrito Chamberí', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000008') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219229', 'Servicio de Servicios a la Ciudadanía del Distrito Chamberí', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007039') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007051', 'Departamento Servicios Sociales del Distrito Chamberí', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10219229') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000009', 'Distrito Fuencarral-El Pardo', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007055', 'Coordinación del Distrito Fuencarral-El Pardo', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000009') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219234', 'Servicio de Servicios a la Ciudadanía del Distrito Fuencarral-El Pardo', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007055') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007067', 'Departamento Servicios Sociales del Distrito Fuencarral-El Pardo', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10219234') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000010', 'Distrito Moncloa-Aravaca', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007072', 'Coordinación del Distrito Moncloa-Aravaca', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000010') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219178', 'Servicio de Servicios a la Ciudadanía del Distrito Moncloa-Aravaca', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007072') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007084', 'Departamento Servicios Sociales del Distrito Moncloa-Aravaca', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10219178') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000011', 'Distrito Latina', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007090', 'Coordinación del Distrito Latina', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000011') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219188', 'Servicio de Servicios a la Ciudadanía del Distrito Latina', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007090') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007102', 'Departamento Servicios Sociales del Distrito Latina', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10219188') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000012', 'Distrito Carabanchel', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007106', 'Coordinación del Distrito Carabanchel', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000012') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219183', 'Servicio de Servicios a la Ciudadanía del Distrito Carabanchel', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007106') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007118', 'Departamento Servicios Sociales del Distrito Carabanchel', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10219183') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000013', 'Distrito Usera', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007124', 'Coordinación del Distrito Usera', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000013') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219193', 'Servicio de Servicios a la Ciudadanía del Distrito Usera', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007124') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007136', 'Departamento Servicios Sociales del Distrito Usera', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10219193') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000014', 'Distrito Puente de Vallecas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007141', 'Coordinación del Distrito Puente de Vallecas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000014') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10218935', 'Servicio de Servicios a la Ciudadanía del Distrito Puente de Vallecas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007141') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007153', 'Departamento Servicios Sociales del Distrito Puente de Vallecas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10218935') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000015', 'Distrito Moratalaz', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007158', 'Coordinación del Distrito Moratalaz', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000015') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10218941', 'Servicio de Servicios a la Ciudadanía del Distrito Moratalaz', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007158') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007170', 'Departamento Servicios Sociales del Distrito Moratalaz', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10218941') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000016', 'Distrito Ciudad Lineal', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007174', 'Coordinación del Distrito Ciudad Lineal', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000016') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219200', 'Servicio de Servicios a la Ciudadanía del Distrito Ciudad Lineal', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007174') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007186', 'Departamento Servicios Sociales del Distrito Ciudad Lineal', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10219200') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000017', 'Distrito Hortaleza', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007190', 'Coordinación del Distrito Hortaleza', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000017') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219198', 'Servicio de Servicios a la Ciudadanía del Distrito Hortaleza', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007190') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007202', 'Departamento Servicios Sociales del Distrito Hortaleza', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10219198') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000018', 'Distrito Villaverde', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007206', 'Coordinación del Distrito Villaverde', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000018') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219154', 'Servicio de Servicios a la Ciudadanía del Distrito Villaverde', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007206') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007218', 'Departamento Servicios Sociales del Distrito Villaverde', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10219154') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000019', 'Distrito Villa de Vallecas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007222', 'Coordinación del Distrito Villa de Vallecas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000019') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219160', 'Servicio de Servicios a la Ciudadanía del Distrito Villa de Vallecas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007222') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007234', 'Departamento Servicios Sociales del Distrito Villa de Vallecas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10219160') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000020', 'Distrito Vicálvaro', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007238', 'Coordinación del Distrito Vicálvaro', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000020') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219165', 'Servicio de Servicios a la Ciudadanía del Distrito Vicálvaro', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007238') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007250', 'Departamento Servicios Sociales del Distrito Vicálvaro', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10219165') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000021', 'Distrito San Blas-Canillejas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10006155', 'Coordinación del Distrito San Blas-Canillejas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000021') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219205', 'Servicio de Servicios a la Ciudadanía del Distrito San Blas-Canillejas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10006155') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007265', 'Departamento Servicios Sociales del Distrito San Blas-Canillejas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10219205') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10000022', 'Distrito Barajas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIST'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10006164', 'Coordinación del Distrito Barajas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'COOR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10000022') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10218946', 'Servicio de Servicios a la Ciudadanía del Distrito Barajas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SERV'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10006164') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007280', 'Departamento Servicios Sociales del Distrito Barajas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10218946') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10005936', 'Dirección General de Mayores y Prevención de la Soledad No Deseada',(select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007601', 'Subdirección General de Mayores y Prevención de la Soledad no Deseada', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SDIR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10005936') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10004089', 'Departamento de Servicios de Ayuda a Domicilio', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007601') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10005937', 'Departamento de Centros de Día y Residenciales', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007601') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10005938', 'Departamento de Programación, Evaluación y Desarrollo', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007601') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10203350', 'Departamento de Coordinación y Seguimiento de la Dependencia', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007601') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10227501', 'Departamento de Apoyo Administrativo', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007601') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10005939', 'Dirección General de Familia e Infancia',(select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10007602', 'Subdirección General de Familia e Infancia', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SDIR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10005939') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10002061', 'Departamento de Prevención del Riesgo Social en la Infancia', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007602') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10005940', 'Departamento de Protección a la Infancia y Adolescencia', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007602') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10005942', 'Departamento de Familia', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007602') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10219001', 'Departamento Jurídico y de Asuntos Generales', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10007602') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10005946', 'Dirección General de Inclusión Social y Cooperación al Desarrollo',(select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10004711', 'Subdirección General de Inclusión Social', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SDIR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10005946') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10005945', 'Departamento de Convivencia e Integración', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10004711') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10222614', 'Departamento de Prevención del Sinhogarismo y Atención a Personas sin Hogar', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10004711') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10214926', 'Dirección General de Servicios Sociales y Atención a la Discapacidad',(select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10207500', 'Subdirección General de Servicios Sociales y Emergencia Social', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SDIR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10214926') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10220375', 'Subdirección General de Innovación Social y Atención a la Discapacidad', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10214926') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10002059', 'Departamento de Coordinación y Programación de la Atención Social Primaria', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10207500') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10005934', 'Departamento de SAMUR Social y Emergencia Social', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10207500') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10216876', 'Departamento de Gestión y Prestaciones en la Atención Social Primaria', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10207500') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10216879', 'Departamento de Prestaciones Económicas y Tarjeta Familias', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10207500') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10225832', 'Departamento de Coordinación Jurídico Administrativa', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10207500') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10224919', 'Departamento de Apoyo a la Discapacidad', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10207500') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10220402', 'Departamento de Sistemas de Información', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10220375') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10220404', 'Departamento de Planificación', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10220375') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10215895', 'Dirección General de Igualdad y Contra la Violencia de Género',(select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10215894', 'Subdirección General de Igualdad y Diversidad', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SDIR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10215895') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10215896', 'Subdirección General de Prevención y Atención Frente a la Violencia de Genero', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10215895') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10207409', 'Departamento de Apoyo Técnico', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10215894') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10207410', 'Departamento de Igualdad y Diversidad', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10215894') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10216641', 'Departamento de Atención a la Violencia de Pareja/Expareja', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10215896') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10227152', 'Departamento de Otras Violencias', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10215896') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10225897', 'Dirección General de Educación, Juventud y Voluntariado',(select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DIR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', NULL);

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10005250', 'Subdirección General de Educación y Juventud', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'SDIR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10225897') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10001061', 'Departamento de Asuntos Jurídicos y Personal en Centros Docentes', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10005250') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10214729', 'Departamento de Educación Infantil', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10005250') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10218780', 'Departamento de Programas Educativos', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10005250') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10002381', 'Departamento de Actividades Educativas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10005250') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10008908', 'Departamento de Coordinación y Enseñanzas Artísticas', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10005250') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10222837', 'Departamento de Progr. Socioeducativos Conciliación de Vida Familiar y Laboral', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10005250') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10223676', 'Departamento de Contratación', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10005250') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10227490', 'Departamento de Contratación II', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10005250') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10002857', 'Departamento de Juventud', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10005250') );

INSERT INTO bssos.REPO_UNIDADES_ORG (REF_UNIDAD_ORG, TX_UNIDAD_ORG, ID_TIPO_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO, ID_PADRE)
VALUES('10008593', 'Departamento de Voluntariado', (select id_tipo_unidad_org from bssos.REPO_TIPO_UNIDADES_ORG WHERE cd_tipo_unidad_org = 'DPTO'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS', (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE REF_UNIDAD_ORG = '10005250') );

COMMIT;

-------------------- FICHA ADM_TIPO_SUB_AMBITOS ------------------------------------------------------
-- Tipos deSUB AMBITOS ------- 

INSERT INTO BSSOS.ADM_TIPO_SUB_AMBITOS (CD_TIPO_SUB_AMBITO, TX_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('DEFAULT', 'DEFAULT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;


-------------------- FICHA ADM_AMBITOS ------------------------------------------------------
-- Datos de AMBITOS ------- 

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('SERVDOM', 'Servicios Domiciliarios', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('DEPEN', 'Dependencia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('CDIARESI', 'Centros de dia y Residencias', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('CMM', 'Centros de mayores', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('SOLEDADND', 'Soledad no deseada', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('CAI', 'Red CAI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('CAF', 'Red CAF + Casa Grande', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('PEF', 'PEF+CIP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('SERCAF', 'SERCAF', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('ASPA', 'RED ASPA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('EDSOC', 'Educación Social', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('CDIAINF', 'Centro de dia - Infancia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('PSH', 'Persona sin hogar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('CONVINM', 'Convivencia e inmigración', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('CCREAL', 'Comisionado Cañada Real', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('ASP', 'Atención Social Primaria', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('OIP', 'OIP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('OFTF', 'Oficina Tarjeta Familia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('SAMUR', 'SAMUR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('SAER', 'SAER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('DISC', 'Discapacidad', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('ESPIG', 'Red Espacios de Igualdad', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('LGTBI', 'Servicios LGTBI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('VGPAREJA', 'Violencia de género pareja y expareja', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('VGEXPSEX', 'Violencia de género Trata y/o explotación sexual', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('VGSEX', 'Violencia de género sexual', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('CJUV', 'Red Centros Juventud + Oficinas IJ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('QUEDAT', 'Red QUEDAT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('ABSENT', 'Absentismo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_AMBITOS (CD_AMBITO, TX_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('RISI', 'Residencia Infantil San Ildefonso', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;


-------------------- FICHA ADM_SUBAMBITOS ------------------------------------------------------
-- Datos de SUBAMBITOS ------- 

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_SERVDOM', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'SERVDOM'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_DEPEN', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'DEPEN'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_CDIARESI', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'CDIARESI'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_CMM', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'CMM'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_SOLEDADND', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'SOLEDADND'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_CAI', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'CAI'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_CAF', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'CAF'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_PEF', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'PEF'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_SERCAF', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'SERCAF'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_ASPA', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'ASPA'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_EDSOC', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'EDSOC'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_CDIAINF', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'CDIAINF'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_PSH', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'PSH'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_CONVINM', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'CONVINM'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_CCREAL', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'CCREAL'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;


INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_ASP', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'ASP'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_OIP', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'OIP'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_OFTF', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'OFTF'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_SAMUR', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'SAMUR'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_SAER', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'SAER'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_DISC', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'DISC'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;


INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_ESPIG', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'ESPIG'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_LGTBI', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'LGTBI'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_VGPAREJA', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'VGPAREJA'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_VGEXPSEX', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'VGEXPSEX'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_VGSEX', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'VGSEX'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;


INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_CJUV', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'CJUV'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_QUEDAT', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'QUEDAT'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_ABSENT', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'ABSENT'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_SUB_AMBITOS (CD_SUB_AMBITO, TX_SUB_AMBITO, ID_AMBITO, ID_TIPO_SUB_AMBITO, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES('GRAL_RISI', 'General', (select id_ambito from bssos.adm_ambitos WHERE cd_ambito = 'RISI'),  (select id_tipo_sub_ambito from bssos.adm_tipo_sub_ambitos WHERE cd_tipo_sub_ambito = 'DEFAULT'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;


-------------------- FICHA ADM_UNIDADES_ORG_X_SUBAMBITOS ------------------------------------------------------
-- Datos de ADM_UNIDADES_ORG_X_SUBAMBITOS  ------- 

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_SERVDOM'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10004089'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_DEPEN'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10203350'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_CDIARESI'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10005937'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_CMM'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10005937'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_SOLEDADND'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10005938'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_CAI'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10005940'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_CAF'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10005942'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_PEF'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10005942'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_SERCAF'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10005942'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_ASPA'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10002061'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_EDSOC'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10002061'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_CDIAINF'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10002061'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;



INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_PSH'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10222614'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;
INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_CONVINM'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10005945'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;
/*
INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_CCREAL'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = 'NULL'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;
*/

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_ASP'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10002059'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_OIP'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10002059'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_OFTF'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10216879'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_SAMUR'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10005934'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_SAER'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10216876'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_DISC'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10224919'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_ESPIG'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10207410'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_LGTBI'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10207410'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_VGPAREJA'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10216641'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_VGEXPSEX'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10227152'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_VGSEX'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10227152'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_CJUV'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10002857'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_QUEDAT'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10218780'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_ABSENT'), (select id_unidad_org from bssos.REPO_UNIDADES_ORG WHERE ref_unidad_org = '10218780'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;

INSERT INTO BSSOS.ADM_UNIDADES_ORG_X_SUB_AMBITOS (ID_SUB_AMBITO, ID_UNIDAD_ORG, FEC_ALTA, FEC_MODIF, FEC_BAJA, AUDIT_USUARIO)
VALUES((select id_sub_ambito from bssos.adm_sub_ambitos WHERE cd_sub_ambito = 'GRAL_RISI'), (select id_unidad_org from bssos.repo_unidades_org WHERE ref_unidad_org = '10218780'),  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ANONYMOUS');
COMMIT;


REFRESH MATERIALIZED VIEW bssos.v_repo_unidades_org_areas;
REFRESH MATERIALIZED VIEW bssos.v_repo_unidades_org_distritos;


COMMIT;

